project_id = "exhlxcigncuqaichgbmy"

[api]
port = 54321
schemas = ["public", "auth"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/**"]
jwt_expiry = 3600
enable_signup = true

[auth.external.google]
enabled = false

[storage]
enabled = true

[inbucket]
port = 54324

[functions.chess-database-search]
verify_jwt = false

[functions.verify-human]
verify_jwt = false
